name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env: 
  app_id: ${{ secrets.APP_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set FLASK_ENV for production
        run: echo "FLASK_ENV=production" >> $GITHUB_ENV

      - name: Create and set up virtual environment
        run: |
          python3 -m venv .venv
          .venv/bin/pip install --upgrade pip
          .venv/bin/pip install -r requirements.txt

      - name: Start Flask server in background
        run: |
          FLASK_APP=app.py .venv/bin/flask run &
          echo $! > flask_pid.txt
          sleep 15

      - name: Stop Flask background server
        if: always()
        run: |
          if [ -f flask_pid.txt ]; then
            kill -SIGINT $(cat flask_pid.txt)
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/cmsc495:latest


      
     
